import mongoose from "mongoose";

const bookingSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: true,
  },
  hotelId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Hotel",
    required: true,
  },
  checkIn: {
    type: Date,
    required: true,
  },
  checkOut: {
    type: Date,
    required: true,
  },
  roomNumber: {
    type: Number,
    required: false, // Auto-generated
  },
  paymentStatus: {
    type: String,
    enum: ["PENDING", "PAID", "FAILED", "REFUNDED"],
    default: "PENDING",
  },
  status: {
    type: String,
    enum: ["CONFIRMED", "CANCELLED", "COMPLETED", "PENDING", "PAID"],
    default: "PENDING",
  },
  totalPrice: {
    type: Number,
    required: true,
  },
  bookingReference: {
    type: String,
    required: false, // Will be generated by pre-save hook
  },
  guestCount: {
    type: Number,
    default: 1,
    min: 1,
  },
  specialRequests: {
    type: String,
    maxlength: 500,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

// Generate unique booking reference and room number before saving
bookingSchema.pre('save', function(next) {
  if (this.isNew) {
    // Generate booking reference if not set
    if (!this.bookingReference) {
      const timestamp = Date.now().toString(36);
      const random = Math.random().toString(36).substr(2, 5);
      this.bookingReference = `BK-${timestamp}-${random}`.toUpperCase();
    }
    // Auto-generate room number if not set
    if (!this.roomNumber) {
      this.roomNumber = Math.floor(1000 + Math.random() * 9000);
    }
  }
  this.updatedAt = new Date();
  next();
});

// Ensure bookingReference is always set after save
bookingSchema.post('save', function(doc) {
  if (!doc.bookingReference) {
    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).substr(2, 5);
    doc.bookingReference = `BK-${timestamp}-${random}`.toUpperCase();
    doc.save();
  }
});

// Index for better query performance
bookingSchema.index({ userId: 1 });
bookingSchema.index({ hotelId: 1 });
bookingSchema.index({ checkIn: 1, checkOut: 1 });
bookingSchema.index({ bookingReference: 1 });

const Booking = mongoose.model("Booking", bookingSchema);

export default Booking;
